### ISSUE TITLE
 Rebuilding with 'apktool --use-aapt2' Failed

### ISSUE THREAD

**Issue by mancioshell** [TheDauntless/patch-apk#5]
W: /tmp/tmp8a7es3z6/com.quadronica.guida-base/AndroidManifest.xml:31: error: attribute android:enableOnBackInvokedCallback not found.
W: error: failed processing manifest.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_41694101682599410788189231143283950118.tmp, link, -o, /tmp/APKTOOL3337719741157442205.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 34, --version-code, 37, --version-name, 5.0.3, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, /tmp/APKTOOL6387700800148185793.tmp, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, --manifest, /tmp/tmp8a7es3z6/com.quadronica.guida-base/AndroidManifest.xml, /tmp/tmp8a7es3z6/com.quadronica.guida-base/build/resources.zip]
Error: Failed to run 'apktool b /tmp/tmp8a7es3z6/com.quadronica.guida-base'.
Run with --debug-output for more information.

I have solved upgrading apktool from 2.6.1 to 2.8.1. But if i upgrade it, i found a warning on your script:

WARNING: currently installed apktool version 2.8.1 is not the same as what this version of this script is developed for (2.6.1), you may suffer from build failures, bugs, and obsolete patches

**Comment by TheDauntless** [comment]
I've removed the warning. If anything breaks, people can just open an issue anyway. This script will need to be updated alongside apktool anyway.
